name: primary-seq-env
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- appnope
- awscli
- bamtools
- bcftools==1.7
- blast
- beagle
- bedops
- bedtools
- bwa
- freebayes==1.0.2
- datamash
- decorator
- fastqc
- fastx_toolkit
- gatk4
- jq
- jedi
- ibdseq
- rename
- java-jdk
- multiqc
- muscle
- parallel
- delly
- mosdepth
- goleft
- picard
- primer3
- sambamba
- samtools
- snpeff
- igvtools
- fastx_toolkit
- trimmomatic
- vcflib
- vcftools
- perl-vcftools-vcf 
- vcfanno
- cython
- ipython
- python=3.6
- pybedtools
- pysam
- scikit-learn
- scikit-image
- scikit-bio
- biopython
- networkx
- keras
- pigz
- plink
- telseq
- tabix
- numpy
- cyvcf2
- r-ape==4.1
- r-devtools
- r-essentials
- r-tidyverse
- r-sleuth
- r-vcfr
- r-cowplot
- r-ggmap
- r-regress
- r-jsonlite
- r-testthat
- r-tseries
- r-igraph
- r-svglite
- unzip
- rename
- salmon
- liknorm
- mosdepth
- gsort
- kallisto
- ucsc-bigwigtobedgraph
- bioconductor-phyloseq
- bioconductor-biocinstaller
- bioconductor-biomart
- scikit-allel
prefix: /usr/local/var/pyenv/versions/miniconda3-4.3.27/envs/primary-seq-env
